spring.application.name=todoapp

spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:29319/railway
spring.datasource.username=postgres
spring.datasource.password=LJAGIsIKGRFmQYpsuEPwIjbwsjSHZVQA

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8090}